name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    name: Project Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zsh shfmt shellcheck

      - name: Syntax Check .zshrc
        run: |
          zsh -n src/.zshrc

      - name: Lint .zshrc Formatting
        run: |
          shfmt -d src/.zshrc

      - name: Shellcheck install.sh
        run: |
          shellcheck install.sh

      - name: Shellcheck pre-commit hook
        run: |
          shellcheck git-hooks/pre-commit

      - name: Shellcheck test.sh
        run: |
          shellcheck test.sh

      - name: Check Required Files
        run: |
          test -f src/github-dark.terminal
          test -f README.md
          test -f LICENSE

      - name: Run Tests
        run: |
          ./test.sh
