name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  zsh-lint:
    name: Validate .zshrc Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install zsh
        run: |
          sudo apt update
          sudo apt install -y zsh

      - name: Check .zshrc Syntax
        run: |
          zsh -n src/.zshrc

      - name: Check files
        run: |
          test -f src/github-dark.terminal
          test -f README.md
          test -f LICENSE
