name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    name: Project Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install zsh and shellcheck
        run: |
          sudo apt update
          sudo apt install -y zsh shellcheck

      - name: Lint .zshrc Syntax
        run: |
          zsh -n src/.zshrc

      - name: Lint .zshrc Style
        run: |
          shellcheck src/.zshrc

      - name: Check Required Files
        run: |
          test -f src/github-dark.terminal
          test -f README.md
          test -f LICENSE
